name: Test-all

# Run the workflow when a Pull Request is opened or when changes are pushed to master
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, feat-git-scan]
  pull_request:
    types: [opened, reopened, review_requested]
  pull_request_review:
    types: [dismissed]

jobs:
 release:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2
    with:
      ref: ${{ secrets.GITHUB_REF }}
  - name: sudo apt-get install make gcc-mingw-w64-x86-64 gcc-mingw-w64-i686 mingw-w64
    run: sudo apt install gcc-mingw-w64
  - name: build application
    run: make test
  - name: test all
    run: bin/test all
